name: ParkourRoll
main: com.gmail.liamgomez75.parkourroll.ParkourRoll
version: 2.2.4

commands:
    parkourroll:
        description: configure settings in the plugin!
        aliases: [pkr, parkroll, pkroll]
        usage: /<command> reload
permissions:
    pkr.*:
        description: Gives access to all commands
        default: false
        children:
            pkr.defaults: true
            pkr.admin: true