name: ParkourRoll
main: com.gmail.liamgomez75.parkourroll.ParkourRoll
version: 2.9.6

commands:
    parkourroll:
        description: configure settings in the plugin!
        aliases: [pkr, parkroll, pkroll]
        usage: See '/<command> help' for correct usages
permissions:
    pkr.*:
        description: Gives access to all commands
        default: false
        children:
            pkr.defaults: true
            pkr.admin: true